### ISSUE TITLE
Refactor al programa (manejo de casos, estructura de datos)

### ISSUE THREAD

**Issue by carlosgruiz-dev** [CppVE/elige_tu_camino_cpp#2]
El programa incluye demasiadas llamadas a condicionales. Se puede crear una estructura de datos que contenga las alternativas y qué hacer en caso de cada respuesta.

Se me ocurre que un `struct` y un `vector` pueden ser una solución. algún otro contenedor que se les ocurra?

**Comment by OscarDSanchezJ** [comment]
Todavia tengo problemas manejando estructuras en c++ voy a hacer los cambios cuando los maneje mejor, ¿por cierto como se ven los fork de otras personas?

**Comment by carlosgruiz-dev** [comment]
en el botón que dice forks arriba a la derecha haces click en el número y ves los repos asociados.. 
Respecto a las estructuras de datos podemos crear un `struct` que tenga  como variables, el texto de la historia, las opciones del usuario (texto y posición del siguiente paso en el vector). Así el programa cambia por un bucle que va leyendo los `struct` de un vector y saltando a la opción que el usuario determine (algo así como ir sacando la tarjeta adecuada según la opción que elija el usuario).
